#Copyright 2025 Google LLC.
#SPDX-License-Identifier: Apache-2.0

steps:
  - name: 'docker'
    args:
      - 'buildx'
      - 'create'
      - '--name'
      - 'mybuilder'
      - '--use'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/amd64,linux/arm64'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA'
      - '--push'
      - '.'
options:
  requestedVerifyOption: 'VERIFIED'
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REPO_NAME: gke-demos